echo "We are trying this practical from linux EC2"
echo "We are from batch-25 and learning git/gihub"
echo "Now I become Death The Destroyer of both worlds"
echo " I Just seen openhiemer"
echo "I am making changes on nov 26"
echo "This chenge is in feature branch"